// Generated by Wrangler by running `wrangler types`

interface Env {
	UNIVERSE_REGISTRY: KVNamespace;
	API_KEY: string;
	ENCRYPTION_KEY: string;
	SOCKET: DurableObjectNamespace<import("./src/index").SocketDurableObject>;
	ANALYTICS_ENGINE: AnalyticsEngineDataset;
}
