#:schema node_modules/wrangler/config-schema.json
name = "pulse-server"
main = "src/index.ts"
compatibility_date = "2024-09-25"

assets = { directory = "./ui/dist" }

[[kv_namespaces]]
binding = "UNIVERSE_REGISTRY"
id = "9cb73170e1074f959328a86829caaaf2"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "SOCKET"
class_name = "SocketDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["SocketDurableObject"]
